# Generated by Django 5.0.3 on 2024-03-20 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garden", "0002_userinventory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gardendata",
            old_name="xp",
            new_name="coins",
        ),
    ]
