# Generated by Django 5.0.3 on 2024-03-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden", "0003_rename_xp_gardendata_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinventory",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
