# Generated by Django 5.0.3 on 2024-03-20 23:47

from django.db import migrations

from garden.models import Plant


def create_flowers(apps, schema_editor):
    plant = apps.get_model('garden', 'Plant')
    plant.objects.bulk_create([
        plant(plant_type=choice[0]) for choice in Plant.PlantTypeEnum.choices
    ])


class Migration(migrations.Migration):
    dependencies = [
        ("garden", "0005_plant_remove_gardendata_num_plants_gardendata_plants"),
    ]

    operations = [
        migrations.RunPython(create_flowers),
    ]