# Generated by Django 5.0.3 on 2024-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden", "0006_auto_20240320_2347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="plant_type",
            field=models.CharField(
                choices=[
                    ("bluebell deep", "Bluebell Deep"),
                    ("bluebell lilac", "Bluebell Lilac"),
                    ("bluebell pale", "Bluebell Pale"),
                    ("marigold orange", "Marigold Orange"),
                    ("marigold red", "Marigold Red"),
                    ("marigold yellow", "Marigold Yellow"),
                    ("tulip orange", "Tulip Orange"),
                    ("tulip pink", "Tulip Pink"),
                    ("tulip red", "Tulip Red"),
                    ("tulip yellow", "Tulip Yellow"),
                    ("sunflower", "Sunflower"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
