# Generated by Django 5.0.3 on 2024-03-21 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden", "0008_gardenlayout"),
        ("store", "0003_alter_item_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gardenlayout",
            name="decoration1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decoration1",
                to="store.item",
            ),
        ),
        migrations.AlterField(
            model_name="gardenlayout",
            name="decoration2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decoration2",
                to="store.item",
            ),
        ),
        migrations.AlterField(
            model_name="gardenlayout",
            name="plant1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant1",
                to="garden.plant",
            ),
        ),
        migrations.AlterField(
            model_name="gardenlayout",
            name="plant2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant2",
                to="garden.plant",
            ),
        ),
        migrations.AlterField(
            model_name="gardenlayout",
            name="plant3",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant3",
                to="garden.plant",
            ),
        ),
    ]
