# Generated by Django 5.0.1 on 2024-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_alter_gardenlayout_decoration1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('BB_Deep', 'Bluebell Deep'), ('BB_Lilac', 'Bluebell Lilac'), ('BB_Pale', 'Bluebell Pale'), ('Marigold_Orange', 'Marigold Orange'), ('Marigold_Red', 'Marigold Red'), ('Marigold_Yellow', 'Marigold Yellow'), ('Tuplip_Orange', 'Tulip Orange'), ('Tulip_Pink', 'Tulip Pink'), ('Tulip_Red', 'Tulip Red'), ('Tulip_Yellow', 'Tulip Yellow'), ('Sunflower', 'Sunflower')], max_length=20, unique=True),
        ),
    ]
