# Generated by Django 5.0.3 on 2024-03-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.TextField(
                        choices=[
                            ("gnome", "Gnome"),
                            ("bird_bath", "Bird Bath"),
                            ("trees", "Trees"),
                        ]
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("price", models.IntegerField()),
                (
                    "shop",
                    models.TextField(
                        choices=[
                            ("decorations", "Decorations"),
                            ("consumables", "Consumables"),
                        ]
                    ),
                ),
                ("is_unique", models.BooleanField(default=False)),
            ],
        ),
    ]
