# Generated by Django 5.0.3 on 2024-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_add_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.TextField(
                choices=[
                    ("gnome", "Gnome"),
                    ("bird_bath", "Bird Bath"),
                    ("trees", "Trees"),
                ],
                unique=True,
            ),
        ),
    ]
