# Generated by Django 5.0.2 on 2024-02-26 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("xp", models.IntegerField()),
                ("points", models.IntegerField()),
                ("expiration_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("qr_code_image", models.ImageField(upload_to="qr_codes/")),
                ("qr_type", models.IntegerField(choices=[(1, "Plant"), (2, "XP")])),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
