# Generated by Django 5.0.2 on 2024-02-26 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qrCodes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="qr_code_image",
        ),
    ]
