# Generated by Django 5.0.1 on 2024-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodes', '0003_qrcode_scanned_by_users_alter_qrcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='xp',
            new_name='coins',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_type',
            field=models.IntegerField(choices=[(1, 'Plant'), (2, 'Coins')]),
        ),
    ]
