# Generated by Django 5.0.2 on 2024-02-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrCodes", "0003_qrcode_scanned_by_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
